"""initial schema (PRD §15 step 1)

Revision ID: 0001
Revises:
Create Date: 2026-09-03 14:36:13.796862
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

import sqlalchemy as sa
from alembic import op

SQL_DIR = Path(__file__).resolve().parents[2] / "sql"
PIT_FUNCTIONS = [
    "sa_financials_as_of",
    "sa_shareholdings_as_of",
    "sa_universe_as_of",
    "sa_prices_as_of",
]


revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column(
            "exchange",
            sa.Enum("NSE", "BSE", "BOTH", name="exchange", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("bse_code", sa.String(length=16), nullable=True),
        sa.Column("sector", sa.String(length=64), nullable=False),
        sa.Column("industry", sa.String(length=64), nullable=True),
        sa.Column("listed_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "(is_mock AND ticker LIKE 'MOCK-%%') OR (NOT is_mock AND ticker NOT LIKE 'MOCK-%%')",
            name="ck_companies_mock_ticker",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isin"),
        sa.UniqueConstraint("ticker"),
    )
    op.create_index(op.f("ix_companies_sector"), "companies", ["sector"], unique=False)
    op.create_table(
        "data_quality",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "NSE_ANNOUNCEMENTS",
                "BSE_ANNOUNCEMENTS",
                "FINANCIAL_RESULTS",
                "SHAREHOLDING_PATTERN",
                "PLEDGE_DISCLOSURE",
                "INSIDER_TRADING",
                "BULK_BLOCK_DEALS",
                "ANNUAL_REPORT",
                "CREDIT_RATING",
                "EOD_PRICES",
                "CORPORATE_ACTIONS",
                "SURVEILLANCE_LISTS",
                "INDEX_CONSTITUENTS",
                name="source",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("last_fetch_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_public_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetch_failure_count", sa.Integer(), nullable=False),
        sa.Column("parse_failure_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "source", "is_mock", name="uq_data_quality_company_source"
        ),
    )
    op.create_index(
        op.f("ix_data_quality_company_id"), "data_quality", ["company_id"], unique=False
    )
    op.create_table(
        "raw_documents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "NSE_ANNOUNCEMENTS",
                "BSE_ANNOUNCEMENTS",
                "FINANCIAL_RESULTS",
                "SHAREHOLDING_PATTERN",
                "PLEDGE_DISCLOSURE",
                "INSIDER_TRADING",
                "BULK_BLOCK_DEALS",
                "ANNUAL_REPORT",
                "CREDIT_RATING",
                "EOD_PRICES",
                "CORPORATE_ACTIONS",
                "SURVEILLANCE_LISTS",
                "INDEX_CONSTITUENTS",
                name="source",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", name="uq_raw_documents_sha256"),
    )
    op.create_index(
        op.f("ix_raw_documents_company_id"), "raw_documents", ["company_id"], unique=False
    )
    op.create_index(
        "ix_raw_documents_company_public",
        "raw_documents",
        ["company_id", "public_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_documents_public_at"), "raw_documents", ["public_at"], unique=False
    )
    op.create_table(
        "universe_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("market_cap_cr", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("median_traded_value_30d", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("is_illiquid", sa.Boolean(), nullable=False),
        sa.Column(
            "listing_status",
            sa.Enum(
                "LISTED",
                "SUSPENDED",
                "DELISTED",
                "MERGED",
                name="listingstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "delisting_kind",
            sa.Enum("COMPULSORY", "VOLUNTARY", name="delistingkind", native_enum=False, length=16),
            nullable=True,
        ),
        sa.Column("gsm_stage", sa.Integer(), nullable=True),
        sa.Column("asm_stage", sa.Integer(), nullable=True),
        sa.Column("in_cap_band", sa.Boolean(), nullable=False),
        sa.Column("in_universe", sa.Boolean(), nullable=False),
        sa.Column("config_version", sa.String(length=32), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "snapshot_date", name="uq_universe_company_date"),
    )
    op.create_index(
        "ix_universe_snapshot_date", "universe_snapshots", ["snapshot_date"], unique=False
    )
    op.create_index(
        op.f("ix_universe_snapshots_company_id"), "universe_snapshots", ["company_id"], unique=False
    )
    op.create_table(
        "announcements",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "RESULTS",
                "ORDER_WIN",
                "CAPACITY_EXPANSION",
                "CREDIT_RATING",
                "BOARD_MEETING",
                "RESIGNATION",
                "AUDITOR_CHANGE",
                "FUND_RAISE",
                "PLEDGE",
                "CORPORATE_ACTION",
                "RELATED_PARTY",
                "OTHER",
                name="announcementcategory",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=512), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_announcements_category"), "announcements", ["category"], unique=False)
    op.create_index(
        op.f("ix_announcements_company_id"), "announcements", ["company_id"], unique=False
    )
    op.create_index(
        "ix_announcements_company_public",
        "announcements",
        ["company_id", "public_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_announcements_public_at"), "announcements", ["public_at"], unique=False
    )
    op.create_index(
        op.f("ix_announcements_raw_document_id"), "announcements", ["raw_document_id"], unique=False
    )
    op.create_table(
        "bulk_deals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "deal_type",
            sa.Enum("BULK", "BLOCK", name="dealtype", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("client_name", sa.String(length=200), nullable=False),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="tradeside", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("value_inr", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bulk_deals_company_id"), "bulk_deals", ["company_id"], unique=False)
    op.create_index(
        "ix_bulk_deals_company_public", "bulk_deals", ["company_id", "public_at"], unique=False
    )
    op.create_index(op.f("ix_bulk_deals_public_at"), "bulk_deals", ["public_at"], unique=False)
    op.create_index(
        op.f("ix_bulk_deals_raw_document_id"), "bulk_deals", ["raw_document_id"], unique=False
    )
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "SPLIT",
                "BONUS",
                "RIGHTS",
                "BUYBACK",
                "DIVIDEND",
                "NAME_CHANGE",
                name="corporateactiontype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("ratio_numerator", sa.Integer(), nullable=True),
        sa.Column("ratio_denominator", sa.Integer(), nullable=True),
        sa.Column("amount_per_share", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("announced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("details", sa.String(length=512), nullable=True),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_corporate_actions_company_ex",
        "corporate_actions",
        ["company_id", "ex_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_corporate_actions_company_id"), "corporate_actions", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_corporate_actions_public_at"), "corporate_actions", ["public_at"], unique=False
    )
    op.create_index(
        op.f("ix_corporate_actions_raw_document_id"),
        "corporate_actions",
        ["raw_document_id"],
        unique=False,
    )
    op.create_table(
        "credit_ratings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("agency", sa.String(length=64), nullable=False),
        sa.Column("instrument", sa.String(length=128), nullable=False),
        sa.Column("rating", sa.String(length=32), nullable=False),
        sa.Column("outlook", sa.String(length=32), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "UPGRADE",
                "DOWNGRADE",
                "REAFFIRMED",
                "ASSIGNED",
                "WITHDRAWN",
                name="ratingaction",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("rating_date", sa.Date(), nullable=False),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credit_ratings_company_id"), "credit_ratings", ["company_id"], unique=False
    )
    op.create_index(
        "ix_credit_ratings_company_public",
        "credit_ratings",
        ["company_id", "public_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credit_ratings_public_at"), "credit_ratings", ["public_at"], unique=False
    )
    op.create_index(
        op.f("ix_credit_ratings_raw_document_id"),
        "credit_ratings",
        ["raw_document_id"],
        unique=False,
    )
    op.create_table(
        "document_texts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "TEXT",
                "TABLE",
                "OCR",
                "STRUCTURED",
                name="extractionmethod",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("page_offsets", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "raw_document_id", "parser_version", name="uq_document_texts_doc_parser"
        ),
    )
    op.create_index(
        op.f("ix_document_texts_raw_document_id"),
        "document_texts",
        ["raw_document_id"],
        unique=False,
    )
    op.create_table(
        "filings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "filing_type",
            sa.Enum(
                "QUARTERLY_RESULTS",
                "ANNUAL_RESULTS",
                "SHAREHOLDING_PATTERN",
                "ANNUAL_REPORT",
                "PLEDGE_DISCLOSURE",
                "INSIDER_DISCLOSURE",
                "ANNOUNCEMENT",
                name="filingtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_filings_company_id"), "filings", ["company_id"], unique=False)
    op.create_index(
        "ix_filings_company_public", "filings", ["company_id", "public_at"], unique=False
    )
    op.create_index(op.f("ix_filings_public_at"), "filings", ["public_at"], unique=False)
    op.create_index(
        op.f("ix_filings_raw_document_id"), "filings", ["raw_document_id"], unique=False
    )
    op.create_table(
        "index_constituents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("index_name", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_index_constituents_company_id"), "index_constituents", ["company_id"], unique=False
    )
    op.create_index(
        "ix_index_constituents_index_dates",
        "index_constituents",
        ["index_name", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_index(
        op.f("ix_index_constituents_public_at"), "index_constituents", ["public_at"], unique=False
    )
    op.create_index(
        op.f("ix_index_constituents_raw_document_id"),
        "index_constituents",
        ["raw_document_id"],
        unique=False,
    )
    op.create_table(
        "insider_trades",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("person_name", sa.String(length=200), nullable=False),
        sa.Column(
            "person_category",
            sa.Enum(
                "PROMOTER",
                "PROMOTER_GROUP",
                "DIRECTOR",
                "KMP",
                "OTHER",
                name="personcategory",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="tradeside", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum(
                "MARKET",
                "OFF_MARKET",
                "PREFERENTIAL",
                "ESOP",
                "GIFT",
                name="trademode",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("value_inr", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_insider_trades_company_id"), "insider_trades", ["company_id"], unique=False
    )
    op.create_index(
        "ix_insider_trades_company_public",
        "insider_trades",
        ["company_id", "public_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insider_trades_public_at"), "insider_trades", ["public_at"], unique=False
    )
    op.create_index(
        op.f("ix_insider_trades_raw_document_id"),
        "insider_trades",
        ["raw_document_id"],
        unique=False,
    )
    op.create_table(
        "pledge_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "CREATION",
                "RELEASE",
                "INVOCATION",
                name="pledgeeventtype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("holder_name", sa.String(length=200), nullable=False),
        sa.Column("shares", sa.BigInteger(), nullable=False),
        sa.Column("pct_of_promoter_holding", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("pct_of_total_shares", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pledge_events_company_id"), "pledge_events", ["company_id"], unique=False
    )
    op.create_index(
        "ix_pledge_events_company_public",
        "pledge_events",
        ["company_id", "public_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pledge_events_public_at"), "pledge_events", ["public_at"], unique=False
    )
    op.create_index(
        op.f("ix_pledge_events_raw_document_id"), "pledge_events", ["raw_document_id"], unique=False
    )
    op.create_table(
        "prices",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("high", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("low", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("close", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("traded_value", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("delivery_pct", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "trade_date", "parser_version", name="uq_prices_company_date"
        ),
    )
    op.create_index("ix_prices_company_date", "prices", ["company_id", "trade_date"], unique=False)
    op.create_index(op.f("ix_prices_company_id"), "prices", ["company_id"], unique=False)
    op.create_index(op.f("ix_prices_public_at"), "prices", ["public_at"], unique=False)
    op.create_index(op.f("ix_prices_raw_document_id"), "prices", ["raw_document_id"], unique=False)
    op.create_table(
        "surveillance_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "framework",
            sa.Enum("GSM", "ASM", name="surveillanceframework", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column(
            "event",
            sa.Enum(
                "ENTRY",
                "EXIT",
                "STAGE_CHANGE",
                name="surveillanceeventtype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.Integer(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_surveillance_company_public",
        "surveillance_events",
        ["company_id", "public_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_surveillance_events_company_id"),
        "surveillance_events",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_surveillance_events_public_at"), "surveillance_events", ["public_at"], unique=False
    )
    op.create_index(
        op.f("ix_surveillance_events_raw_document_id"),
        "surveillance_events",
        ["raw_document_id"],
        unique=False,
    )
    op.create_table(
        "financials",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("filing_id", sa.BigInteger(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period_months", sa.Integer(), nullable=False),
        sa.Column("consolidated", sa.Boolean(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "TEXT",
                "TABLE",
                "OCR",
                "STRUCTURED",
                name="extractionmethod",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("other_income", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("total_expenses", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("ebitda", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("depreciation", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("finance_cost", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("pbt", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("tax", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("pat", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("eps", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("total_borrowings", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("short_term_borrowings", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("long_term_borrowings", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("cash_and_equivalents", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("receivables", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("inventory", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("payables", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("net_worth", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("total_assets", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("shares_outstanding", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("cfo", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("cfi", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("cff", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("capex", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("related_party_revenue", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("contingent_liabilities", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column(
            "audit_opinion",
            sa.Enum(
                "UNQUALIFIED",
                "EMPHASIS_OF_MATTER",
                "QUALIFIED",
                "GOING_CONCERN",
                "ADVERSE",
                "DISCLAIMER",
                name="auditopinion",
                native_enum=False,
                length=24,
            ),
            nullable=True,
        ),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_superseded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["filing_id"], ["filings.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id",
            "period_end",
            "period_months",
            "consolidated",
            "filing_id",
            "parser_version",
            name="uq_financials_period_filing",
        ),
    )
    op.create_index(op.f("ix_financials_company_id"), "financials", ["company_id"], unique=False)
    op.create_index(
        "ix_financials_company_period",
        "financials",
        ["company_id", "period_end", "consolidated"],
        unique=False,
    )
    op.create_index(op.f("ix_financials_filing_id"), "financials", ["filing_id"], unique=False)
    op.create_index(op.f("ix_financials_public_at"), "financials", ["public_at"], unique=False)
    op.create_index(
        op.f("ix_financials_raw_document_id"), "financials", ["raw_document_id"], unique=False
    )
    op.create_table(
        "shareholdings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.BigInteger(), nullable=False),
        sa.Column("filing_id", sa.BigInteger(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("promoter_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("promoter_pledged_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("fii_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("dii_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("public_pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("total_shareholders", sa.Integer(), nullable=False),
        sa.Column("retail_shareholders", sa.Integer(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "TEXT",
                "TABLE",
                "OCR",
                "STRUCTURED",
                name="extractionmethod",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_superseded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["filing_id"], ["filings.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id",
            "period_end",
            "filing_id",
            "parser_version",
            name="uq_shareholdings_period",
        ),
    )
    op.create_index(
        op.f("ix_shareholdings_company_id"), "shareholdings", ["company_id"], unique=False
    )
    op.create_index(
        "ix_shareholdings_company_period",
        "shareholdings",
        ["company_id", "period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shareholdings_filing_id"), "shareholdings", ["filing_id"], unique=False
    )
    op.create_index(
        op.f("ix_shareholdings_public_at"), "shareholdings", ["public_at"], unique=False
    )
    op.create_index(
        op.f("ix_shareholdings_raw_document_id"), "shareholdings", ["raw_document_id"], unique=False
    )
    op.create_table(
        "institutional_holdings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("shareholding_id", sa.BigInteger(), nullable=False),
        sa.Column("holder_name", sa.String(length=200), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "FII",
                "DII",
                "MUTUAL_FUND",
                "INSURANCE",
                "OTHER",
                name="holdercategory",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("pct", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["shareholding_id"], ["shareholdings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_institutional_holdings_shareholding_id"),
        "institutional_holdings",
        ["shareholding_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute((SQL_DIR / "pit_functions_v1.sql").read_text())


def downgrade() -> None:
    for fn in PIT_FUNCTIONS:
        op.execute(f"DROP FUNCTION IF EXISTS {fn}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_institutional_holdings_shareholding_id"), table_name="institutional_holdings"
    )
    op.drop_table("institutional_holdings")
    op.drop_index(op.f("ix_shareholdings_raw_document_id"), table_name="shareholdings")
    op.drop_index(op.f("ix_shareholdings_public_at"), table_name="shareholdings")
    op.drop_index(op.f("ix_shareholdings_filing_id"), table_name="shareholdings")
    op.drop_index("ix_shareholdings_company_period", table_name="shareholdings")
    op.drop_index(op.f("ix_shareholdings_company_id"), table_name="shareholdings")
    op.drop_table("shareholdings")
    op.drop_index(op.f("ix_financials_raw_document_id"), table_name="financials")
    op.drop_index(op.f("ix_financials_public_at"), table_name="financials")
    op.drop_index(op.f("ix_financials_filing_id"), table_name="financials")
    op.drop_index("ix_financials_company_period", table_name="financials")
    op.drop_index(op.f("ix_financials_company_id"), table_name="financials")
    op.drop_table("financials")
    op.drop_index(op.f("ix_surveillance_events_raw_document_id"), table_name="surveillance_events")
    op.drop_index(op.f("ix_surveillance_events_public_at"), table_name="surveillance_events")
    op.drop_index(op.f("ix_surveillance_events_company_id"), table_name="surveillance_events")
    op.drop_index("ix_surveillance_company_public", table_name="surveillance_events")
    op.drop_table("surveillance_events")
    op.drop_index(op.f("ix_prices_raw_document_id"), table_name="prices")
    op.drop_index(op.f("ix_prices_public_at"), table_name="prices")
    op.drop_index(op.f("ix_prices_company_id"), table_name="prices")
    op.drop_index("ix_prices_company_date", table_name="prices")
    op.drop_table("prices")
    op.drop_index(op.f("ix_pledge_events_raw_document_id"), table_name="pledge_events")
    op.drop_index(op.f("ix_pledge_events_public_at"), table_name="pledge_events")
    op.drop_index("ix_pledge_events_company_public", table_name="pledge_events")
    op.drop_index(op.f("ix_pledge_events_company_id"), table_name="pledge_events")
    op.drop_table("pledge_events")
    op.drop_index(op.f("ix_insider_trades_raw_document_id"), table_name="insider_trades")
    op.drop_index(op.f("ix_insider_trades_public_at"), table_name="insider_trades")
    op.drop_index("ix_insider_trades_company_public", table_name="insider_trades")
    op.drop_index(op.f("ix_insider_trades_company_id"), table_name="insider_trades")
    op.drop_table("insider_trades")
    op.drop_index(op.f("ix_index_constituents_raw_document_id"), table_name="index_constituents")
    op.drop_index(op.f("ix_index_constituents_public_at"), table_name="index_constituents")
    op.drop_index("ix_index_constituents_index_dates", table_name="index_constituents")
    op.drop_index(op.f("ix_index_constituents_company_id"), table_name="index_constituents")
    op.drop_table("index_constituents")
    op.drop_index(op.f("ix_filings_raw_document_id"), table_name="filings")
    op.drop_index(op.f("ix_filings_public_at"), table_name="filings")
    op.drop_index("ix_filings_company_public", table_name="filings")
    op.drop_index(op.f("ix_filings_company_id"), table_name="filings")
    op.drop_table("filings")
    op.drop_index(op.f("ix_document_texts_raw_document_id"), table_name="document_texts")
    op.drop_table("document_texts")
    op.drop_index(op.f("ix_credit_ratings_raw_document_id"), table_name="credit_ratings")
    op.drop_index(op.f("ix_credit_ratings_public_at"), table_name="credit_ratings")
    op.drop_index("ix_credit_ratings_company_public", table_name="credit_ratings")
    op.drop_index(op.f("ix_credit_ratings_company_id"), table_name="credit_ratings")
    op.drop_table("credit_ratings")
    op.drop_index(op.f("ix_corporate_actions_raw_document_id"), table_name="corporate_actions")
    op.drop_index(op.f("ix_corporate_actions_public_at"), table_name="corporate_actions")
    op.drop_index(op.f("ix_corporate_actions_company_id"), table_name="corporate_actions")
    op.drop_index("ix_corporate_actions_company_ex", table_name="corporate_actions")
    op.drop_table("corporate_actions")
    op.drop_index(op.f("ix_bulk_deals_raw_document_id"), table_name="bulk_deals")
    op.drop_index(op.f("ix_bulk_deals_public_at"), table_name="bulk_deals")
    op.drop_index("ix_bulk_deals_company_public", table_name="bulk_deals")
    op.drop_index(op.f("ix_bulk_deals_company_id"), table_name="bulk_deals")
    op.drop_table("bulk_deals")
    op.drop_index(op.f("ix_announcements_raw_document_id"), table_name="announcements")
    op.drop_index(op.f("ix_announcements_public_at"), table_name="announcements")
    op.drop_index("ix_announcements_company_public", table_name="announcements")
    op.drop_index(op.f("ix_announcements_company_id"), table_name="announcements")
    op.drop_index(op.f("ix_announcements_category"), table_name="announcements")
    op.drop_table("announcements")
    op.drop_index(op.f("ix_universe_snapshots_company_id"), table_name="universe_snapshots")
    op.drop_index("ix_universe_snapshot_date", table_name="universe_snapshots")
    op.drop_table("universe_snapshots")
    op.drop_index(op.f("ix_raw_documents_public_at"), table_name="raw_documents")
    op.drop_index("ix_raw_documents_company_public", table_name="raw_documents")
    op.drop_index(op.f("ix_raw_documents_company_id"), table_name="raw_documents")
    op.drop_table("raw_documents")
    op.drop_index(op.f("ix_data_quality_company_id"), table_name="data_quality")
    op.drop_table("data_quality")
    op.drop_index(op.f("ix_companies_sector"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
